import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {CAMERA_LIMITS,createOrbit,resetOrbit,rotateOrbit,cameraPose,keepOutsideTower,bindOrbitControls} from '../src/camera-controls.js';
test('default camera is identical to original follow pose',()=>{for(const a of [0,1,3,10])for(const r of [6,20,24]){const target={x:Math.cos(a)*(r+7),y:40,z:Math.sin(a)*(r+7)};const pos=cameraPose(target,a,r,createOrbit());assert(Math.abs(pos.x-Math.cos(a-.28)*(r+24))<1e-10);assert(Math.abs(pos.z-Math.sin(a-.28)*(r+24))<1e-10);assert(Math.abs(pos.y-51)<1e-10)}});
test('orbit wraps yaw, clamps pitch, rejects invalid movement and resets',()=>{const o=createOrbit();rotateOrbit(o,1e6,-1e6);assert(o.yaw>=-Math.PI&&o.yaw<Math.PI);assert.equal(o.pitch,CAMERA_LIMITS.pitchMax);rotateOrbit(o,0,1e6);assert.equal(o.pitch,CAMERA_LIMITS.pitchMin);const before={...o};rotateOrbit(o,NaN,Infinity);assert.deepEqual(o,before);resetOrbit(o);assert.deepEqual(o,createOrbit())});
test('free view remains relative to player/track heading and respects ground/tower bounds',()=>{const o=createOrbit();rotateOrbit(o,90,-40);const a=.8,r=20,t={x:Math.cos(a)*27,y:50,z:Math.sin(a)*27};const p=cameraPose(t,a,r,o);const d=.7,t2={x:Math.cos(a+d)*27,y:90,z:Math.sin(a+d)*27},p2=cameraPose(t2,a+d,r,o);assert(Math.abs(p2.y-p.y-40)<1e-9);assert(Math.abs(p2.x-(p.x*Math.cos(d)-p.z*Math.sin(d)))<1e-9);for(let yaw=-Math.PI;yaw<Math.PI;yaw+=.1)for(const pitch of [-.28,0,.72]){const q=cameraPose(t,a,r,{yaw,pitch});assert(Math.hypot(q.x,q.z)>=r+2.5-1e-9);assert(q.y>=2.4);assert(Object.values(q).every(Number.isFinite))}const clipped=keepOutsideTower({x:0,y:-9,z:0},22.5,a);assert.equal(clipped.y,2.4);assert(Math.hypot(clipped.x,clipped.z)>=22.5-1e-9)});
function fixture(){const dom=new JSDOM('<canvas></canvas><button>UI</button>'),w=dom.window,c=w.document.querySelector('canvas'),o=createOrbit();let enabled=true,captured=null;c.setPointerCapture=id=>captured=id;c.hasPointerCapture=id=>captured===id;c.releasePointerCapture=()=>captured=null;const controls=bindOrbitControls(c,o,{isEnabled:()=>enabled});const send=(type,id,x,y,extra={})=>{const e=new w.Event(type,{bubbles:true,cancelable:true});Object.assign(e,{pointerId:id,clientX:x,clientY:y,pointerType:'touch',button:0,...extra});c.dispatchEvent(e)};return {dom,w,c,o,controls,send,setEnabled:v=>enabled=v,get capture(){return captured}}}
test('pointer capture owns one touch, ignores competing touch and clears on up/cancel/lost/blur',()=>{const f=fixture();f.send('pointerdown',1,0,0);assert.equal(f.capture,1);f.send('pointermove',1,40,-20);const yaw=f.o.yaw;f.send('pointerdown',2,50,50);f.send('pointermove',2,100,100);f.send('pointerup',2,100,100);assert.equal(f.o.yaw,yaw);assert(f.controls.dragging);f.send('pointerup',1,40,-20);assert(!f.controls.dragging);assert.equal(f.capture,null);for(const type of ['pointercancel','lostpointercapture']){f.send('pointerdown',3,0,0);f.send(type,3,0,0);assert(!f.controls.dragging)}f.send('pointerdown',4,0,0);f.w.dispatchEvent(new f.w.Event('blur'));assert(!f.controls.dragging);f.controls.dispose();f.dom.window.close()});
test('disabled or right-button gestures do not rotate; disabling during capture clears it',()=>{const f=fixture();f.setEnabled(false);f.send('pointerdown',1,0,0);f.send('pointermove',1,100,100);assert(!f.controls.dragging);assert.equal(f.o.yaw,0);f.setEnabled(true);f.send('pointerdown',2,0,0,{pointerType:'mouse',button:2});assert(!f.controls.dragging);f.send('pointerdown',3,0,0);f.setEnabled(false);f.send('pointermove',3,100,100);assert(!f.controls.dragging);assert.equal(f.o.yaw,0);f.dom.window.close()});
