import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import * as THREE from 'three';
import {JSDOM} from 'jsdom';
import {CHARACTERS,createRace,stepRace,HAZARDS,SHORTCUTS,ITEM_PICKUPS} from '../src/simulation.js';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const source=fs.readFileSync(new URL('../src/main.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replaceAll('import.meta.env.BASE_URL',"'./'").replace(/init\(\);\s*$/,'');
function app(){const dom=new JSDOM(html,{runScripts:'outside-only',url:'http://localhost'});Object.assign(dom.window,{THREE,CHARACTERS,createRace,stepRace,HAZARDS,SHORTCUTS,ITEM_PICKUPS});dom.window.eval(source+`;window.t={get selected(){return selected},get race(){return race},get paused(){return paused},get playing(){return playing},get keys(){return keys},get actions(){return actionQueue},get touch(){return touch},enable(){scene=new THREE.Scene();CHARACTERS.forEach(c=>templates.set(c.id,new THREE.Group()));loaded=true;},startRace,goMenu,updateHud,endRace,readInput};`);return dom;}
test('ten supplied characters are selectable with matching Chinese text',()=>{const d=app(),w=d.window;assert.equal(w.document.querySelectorAll('#characters button').length,10);w.document.querySelector('[data-id="Lucario"]').click();assert.equal(w.t.selected,'Lucario');assert.equal(w.document.querySelectorAll('#characters .active').length,1);d.window.close()});
test('help and settings open, close and persist auto-forward',()=>{const d=app(),w=d.window;w.document.querySelector('#help').click();assert.match(w.document.querySelector('#modalContent').textContent,/完美格擋/);w.document.querySelector('#helpDone').click();assert(w.document.querySelector('#modal').classList.contains('hidden'));w.document.querySelector('#settings').click();const box=w.document.querySelector('#autoRun');box.checked=true;box.dispatchEvent(new w.Event('change'));assert.equal(JSON.parse(w.localStorage.getItem('101-settings')).autoRun,true);d.window.close()});
test('start, keyboard and touch action bindings, pause close, restart and exit',()=>{const d=app(),w=d.window;w.t.enable();w.document.querySelector('#start').click();assert.equal(w.t.race.racers.length,4);assert.equal(w.t.race.racers[0].characterId,'Greninja');w.dispatchEvent(new w.KeyboardEvent('keydown',{code:'KeyJ'}));assert.equal(w.t.actions.attack,true);w.dispatchEvent(new w.KeyboardEvent('keydown',{code:'KeyW'}));assert(w.t.keys.has('KeyW'));w.dispatchEvent(new w.KeyboardEvent('keyup',{code:'KeyW'}));assert(!w.t.keys.has('KeyW'));w.document.querySelector('[data-action="shield"]').dispatchEvent(new w.Event('pointerdown',{cancelable:true}));assert.equal(w.t.actions.shield,true);w.document.querySelector('#pause').click();assert(w.t.paused);w.document.querySelector('#closeModal').click();assert(!w.t.paused);w.document.querySelector('#pause').click();w.document.querySelector('#restart').click();assert.equal(w.t.race.time,0);assert(!w.t.paused);w.document.querySelector('#pause').click();w.document.querySelector('#exit').click();assert(!w.t.playing);assert(!w.document.querySelector('#menu').classList.contains('hidden'));d.window.close()});
test('result records persist only for actual player finish, rematch works',()=>{const d=app(),w=d.window;w.t.enable();w.t.startRace();const r=w.t.race;r.status='finished';r.winner='player';r.time=194;r.racers[0].progress=101;r.racers[0].finished=true;r.racers[0].finishTime=194;w.t.endRace();assert.equal(JSON.parse(w.localStorage.getItem('101-records'))[0].time,194);w.document.querySelector('#again').click();assert.equal(w.t.race.status,'countdown');assert(!w.t.paused);d.window.close()});

test('swapped directions are consistent on A/D, arrows and touch',()=>{const d=app(),w=d.window;for(const [key,expected] of [['KeyA',1],['KeyD',-1],['ArrowLeft',1],['ArrowRight',-1]]){w.t.keys.clear();w.dispatchEvent(new w.KeyboardEvent('keydown',{code:key}));assert.equal(w.t.readInput().lane,expected)}w.t.keys.clear();w.t.touch.left=true;assert.equal(w.t.readInput().lane,1);w.t.touch.left=false;w.t.touch.right=true;assert.equal(w.t.readInput().lane,-1);d.window.close()});
test('F and mobile fire action queue the actual projectile command and inventory HUD',()=>{const d=app(),w=d.window;w.t.enable();w.t.startRace();w.dispatchEvent(new w.KeyboardEvent('keydown',{code:'KeyF'}));assert.equal(w.t.readInput().fire,true);delete w.t.actions.fire;w.document.querySelector('[data-action="fire"]').dispatchEvent(new w.Event('pointerdown',{cancelable:true}));assert.equal(w.t.actions.fire,true);w.t.race.racers[0].ammo=1;w.t.updateHud();assert.match(w.document.querySelector('#ammo').textContent,/1 發/);w.t.race.racers[0].ammo=0;w.t.updateHud();assert.match(w.document.querySelector('#ammo').textContent,/0 發/);d.window.close()});
