import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {CHARACTERS,createRace,stepRace,HAZARDS,SHORTCUTS,ITEM_PICKUPS} from './simulation.js';
import './style.css';
import {createOrbit,resetOrbit,cameraPose,keepOutsideTower,bindOrbitControls} from './camera-controls.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let selected='Greninja', race=null, paused=false, playing=false, loaded=false, lastEvent=0, resultShown=false;
let renderer,scene,camera,tower,preview,actorViews=[],effects=[],supplyViews=[],itemViews=[],projectileViews=new Map(),last=performance.now(),menuAngle=.7;
const orbit=createOrbit();
const orbitControls=bindOrbitControls($('#world'),orbit,{isEnabled:()=>playing&&!paused&&race?.status!=='finished',onChange:()=>{$('#cameraReset').textContent='↺ 重置視角 C'}});
function resetView(){orbitControls.clear();resetOrbit(orbit);$('#cameraReset').textContent='↺ 跟隨視角 C'}
$('#cameraReset').onclick=resetView;
const templates=new Map(), keys=new Set(), actionQueue={}, touch={forward:false,left:false,right:false};
const vec=new THREE.Vector3(), target=new THREE.Vector3(), clockFormat=t=>`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;
const safeRead=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
let settings=safeRead('101-settings',{volume:.35,quality:'auto',autoRun:false}), records=safeRead('101-records',[]), audio;
const save=(key,v)=>{try{localStorage.setItem(key,JSON.stringify(v))}catch{}};
function beep(f=500,d=.1){if(!audio||settings.volume<=0)return;const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(f*.55,audio.currentTime+d);g.gain.setValueAtTime(settings.volume*.1,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d);}
function setupAudio(){try{audio??=new AudioContext();audio.resume()}catch{}}
function setSelected(id){selected=id;$$('#characters button').forEach(b=>{b.classList.toggle('active',b.dataset.id===id);b.setAttribute('aria-pressed',String(b.dataset.id===id))});$('#characterInfo').textContent=CHARACTERS.find(c=>c.id===id)?.description||'';if(loaded)makePreview()}
for(const c of CHARACTERS){const b=document.createElement('button');b.dataset.id=c.id;b.style.setProperty('--char',c.color);b.innerHTML=`<i></i>${c.name}`;b.onclick=()=>{setSelected(c.id);beep(650)};$('#characters').append(b)}setSelected(selected);
const HELPTEXT=`<div class="eyebrow">HOW TO CLIMB</div><h2>第一個抵達 101F 就贏！</h2><p>沿著台北101外側的螺旋天空步道向上跑。你與3隻電腦寶可夢使用相同的技能規則。</p><ul><li><b>W / ↑：</b>向上攀登；S / ↓ 減速。A / ← 向畫面左側換線，D / → 向畫面右側換線（方向已對調）。手機按住 ▲ 前進。</li><li><b>空白鍵：</b>跳躍，避開風場與障礙；<b>L / Shift：</b>消耗體力加速衝刺。</li><li><b>J：</b>擊退身邊的對手。接近同跑道選手再出招！</li><li><b>F：前射衝擊彈。</b>拾取紫色彈藥箱後按 F 或「前射道具」，沿賽道向前發射，最遠6層。最多存1發，只攻擊前方同線對手；防護罩可擋，完美盾會反擊。</li><li><b>K：</b>防護罩。對手腳下出現紅圈時立刻啟動。護盾前 0.22 秒是<b>完美格擋</b>，能反彈攻擊。</li><li><b>每10層檢查點：</b>掉落後拉回最近檢查點。鑽石補給可恢復體力；落後會獲得追趕加成。</li><li>內圈綠色捷徑可用跳躍通過，成功搶先幾層；金色補給與青色檢查點都值得爭取。</li></ul><p><b>拖曳3D畫面可旋轉視角</b>：滑鼠左鍵或單指拖曳可左右旋轉、上下調整；移動時仍會跟著角色。按 C 或右上「跟隨視角」重置。技能按鈕與方向按鈕不會旋轉鏡頭。</p><p>Esc / P 暫停。可在設定開啟「自動前進」，專心換線與對戰。</p><button class="primary" id="helpDone">知道了</button>`;
let resumeAfterModal=false;
function showModal(html){orbitControls.clear();resumeAfterModal=playing&&!paused;paused=playing||paused;$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden');$('#closeModal').focus()}
function closeModal(){orbitControls.clear(); $('#modal').classList.add('hidden');if(playing&&race?.status!=='finished')paused=false;if(resumeAfterModal){paused=false;resumeAfterModal=false}keys.clear();Object.keys(touch).forEach(k=>touch[k]=false);}
$('#closeModal').onclick=()=>{if(race?.status==='finished')goMenu();else closeModal()};
$('#help').onclick=()=>{showModal(HELPTEXT);$('#helpDone').onclick=closeModal};
$('#records').onclick=()=>showModal(`<div class="eyebrow">PERSONAL BEST</div><h2>我的登頂紀錄</h2>${records.length?records.slice(0,8).map((r,i)=>`<div class="results"><span>${i+1}. ${r.name}</span><b>${clockFormat(r.time)}</b></div>`).join(''):'<p>完成登頂，就能留下第一筆紀錄。紀錄只保存在這台裝置。</p>'}`);
function settingsModal(){showModal(`<div class="eyebrow">YOUR RACE</div><h2>遊戲設定</h2><label>音效 <input id="volume" type="range" min="0" max="1" step="0.05" value="${settings.volume}" aria-label="音效音量"></label><label>畫面品質 <select id="quality"><option value="auto">自動</option><option value="low">省電</option><option value="high">高畫質</option></select></label><label>自動前進 <input id="autoRun" type="checkbox" ${settings.autoRun?'checked':''}></label><p>自動前進仍可用 S 減速。觸控裝置建議開啟，騰出雙手使用技能。</p>`);$('#quality').value=settings.quality;$('#volume').oninput=e=>{settings.volume=+e.target.value;save('101-settings',settings);setupAudio();beep()};$('#quality').onchange=e=>{settings.quality=e.target.value;applyQuality();save('101-settings',settings)};$('#autoRun').onchange=e=>{settings.autoRun=e.target.checked;save('101-settings',settings)}}
$('#settings').onclick=settingsModal;
function pauseModal(){if(!playing)return;paused=true;resumeAfterModal=false;showModal(`<div class="eyebrow">TAKE A BREATH</div><h2>休息一下，再向上。</h2><p>目前 ${Math.floor(race.racers[0].progress)}F · ${clockFormat(race.time)}</p><button id="resume" class="primary">繼續比賽</button><div class="menurow"><button id="raceSettings">設定</button><button id="restart">重新比賽</button><button id="exit">角色選單</button></div>`);$('#resume').onclick=()=>{closeModal();paused=false};$('#restart').onclick=startRace;$('#exit').onclick=goMenu;$('#raceSettings').onclick=()=>{settingsModal();resumeAfterModal=true}}
$('#pause').onclick=pauseModal;
function startRace(){if(!loaded)return;resetView();setupAudio();closeModal();clearActors();race=createRace(selected,Math.floor(Math.random()*1e9));playing=true;paused=false;resultShown=false;lastEvent=0;keys.clear();Object.keys(actionQueue).forEach(k=>delete actionQueue[k]);$('#menu').classList.add('hidden');$('#hud').classList.remove('hidden');if(preview){scene.remove(preview);preview=null}race.racers.forEach((r,i)=>{const g=new THREE.Group(),model=templates.get(r.characterId).clone(true);g.add(model);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.45,.085,8,32),new THREE.MeshBasicMaterial({color:i===0?0x63f5df:CHARACTERS.find(c=>c.id===r.characterId)?.color||0xffffff}));ring.rotation.x=Math.PI/2;ring.position.y=.08;g.add(ring);const shield=new THREE.Mesh(new THREE.SphereGeometry(2.1,18,12),new THREE.MeshBasicMaterial({color:0x5ff5ed,transparent:true,opacity:.25,wireframe:true}));shield.position.y=1.8;shield.visible=false;g.add(shield);scene.add(g);actorViews.push({g,model,shield,ring});});beep(900,.3);}
$('#start').onclick=startRace;
function clearActors(){projectileViews.forEach(m=>{scene.remove(m);m.geometry.dispose();m.material.dispose()});projectileViews.clear();actorViews.forEach(v=>{scene.remove(v.g);v.ring.geometry.dispose();v.ring.material.dispose();v.shield.geometry.dispose();v.shield.material.dispose()});actorViews=[];effects.forEach(e=>{scene.remove(e.mesh);e.mesh.geometry.dispose();e.mesh.material.dispose()});effects=[]}
function goMenu(){resetView();closeModal();playing=false;paused=false;race=null;clearActors();$('#hud').classList.add('hidden');$('#menu').classList.remove('hidden');makePreview()}
function press(action){if(playing&&!paused)actionQueue[action]=true;}
const bindings={Space:'jump',KeyJ:'attack',KeyK:'shield',KeyL:'dash',KeyF:'fire',ShiftLeft:'dash',ShiftRight:'dash'};
addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement)return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.code==='Escape'||e.code==='KeyP'){if(!$('#modal').classList.contains('hidden')){if(race?.status==='finished')goMenu();else closeModal();}else pauseModal();return}if(e.code==='KeyC'&&playing){resetView();return}if(e.code==='Enter'&&!playing&&$('#modal').classList.contains('hidden'))startRace();if(!e.repeat&&bindings[e.code])press(bindings[e.code]);keys.add(e.code)});addEventListener('keyup',e=>keys.delete(e.code));
addEventListener('blur',()=>{keys.clear();Object.keys(touch).forEach(k=>touch[k]=false);if(playing&&!paused)pauseModal()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing&&!paused)pauseModal()});
$$('[data-action]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();press(b.dataset.action)}));$$('[data-move]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);touch[b.dataset.move]=true});['pointerup','pointercancel','lostpointercapture'].forEach(type=>b.addEventListener(type,()=>touch[b.dataset.move]=false))});
let towerRadius=24;const turns=7.4, rise=188/101, startY=14;
const radiusAt=p=>p<25?24-4*p/25:p<77?20:20-14*(p-77)/24;
function pathPoint(progress,lane=1,out=new THREE.Vector3()){const a=progress/101*Math.PI*2*turns,r=radiusAt(progress)+4+lane*3;return out.set(Math.cos(a)*r,startY+progress*rise,Math.sin(a)*r)}
function optimize(root){root.updateMatrixWorld(true);const buckets=new Map();root.traverse(o=>{if(!o.isMesh)return;const geo=o.geometry.clone().applyMatrix4(o.matrixWorld);const mat=Array.isArray(o.material)?o.material[0]:o.material;const k=mat.uuid+Object.keys(geo.attributes).sort().join();if(!buckets.has(k))buckets.set(k,{mat,geos:[]});buckets.get(k).geos.push(geo)});const group=new THREE.Group();for(const b of buckets.values()){let geo;try{geo=mergeGeometries(b.geos,false)}catch{}if(geo){const m=new THREE.Mesh(geo,b.mat);group.add(m);b.geos.forEach(g=>g.dispose())}else b.geos.forEach(g=>group.add(new THREE.Mesh(g,b.mat)))}return group}
function normalize(root,height){const b=new THREE.Box3().setFromObject(root),size=b.getSize(new THREE.Vector3()),center=b.getCenter(new THREE.Vector3());const s=height/size.y;root.position.set(-center.x*s,-b.min.y*s,-center.z*s);root.scale.setScalar(s);const g=new THREE.Group();g.add(root);return g}
function applyQuality(){if(renderer)renderer.setPixelRatio(settings.quality==='low'?1:Math.min(devicePixelRatio,settings.quality==='high'?2:1.5))}
function makePreview(){supplyViews.forEach(v=>v.mesh.visible=true);itemViews.forEach(v=>v.mesh.visible=true);if(preview)scene.remove(preview);preview=templates.get(selected).clone(true);preview.scale.setScalar(2.5);pathPoint(1,1,preview.position);scene.add(preview)}
function stripGeometry(lane){const verts=[],normals=[],indices=[];const steps=101*16;for(let i=0;i<=steps;i++){const p=i/steps*101;for(const edge of [-1,1]){const v=pathPoint(p,lane+edge*.45);verts.push(v.x,v.y-.15,v.z);normals.push(0,1,0)}if(i<steps&&!HAZARDS.some(h=>h.type==='gap'&&h.lane===lane&&p>=h.start-.03&&p<=h.end+.03)){const j=i*2;indices.push(j,j+2,j+1,j+1,j+2,j+3)}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(normals,3));g.setIndex(indices);g.computeVertexNormals();return g}
function buildTrack(){for(let lane=0;lane<3;lane++){const m=new THREE.Mesh(stripGeometry(lane),new THREE.MeshStandardMaterial({color:[0x19434f,0x265365,0x234056][lane],roughness:.52,metalness:.6,side:THREE.DoubleSide}));scene.add(m)}for(const lane of [-.5,.5,1.5,2.5]){const pts=[];for(let p=0;p<=101;p+=.13)pts.push(pathPoint(p,lane).add(new THREE.Vector3(0,.04,0)));scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:lane===-.5||lane===2.5?0x64e9df:0x5b8391,transparent:true,opacity:.8})))}
 const postGeo=new THREE.CylinderGeometry(.09,.09,2,5),postMat=new THREE.MeshStandardMaterial({color:0x73999f});const posts=new THREE.InstancedMesh(postGeo,postMat,204);let n=0;const d=new THREE.Object3D();for(let p=0;p<=101;p++){for(const lane of [-.5,2.5]){pathPoint(p,lane,d.position);d.position.y+=.8;d.updateMatrix();posts.setMatrixAt(n++,d.matrix)}}scene.add(posts);
 for(let p=10;p<=100;p+=10){const g=new THREE.Group(),a=p/101*Math.PI*2*turns;pathPoint(p,1,g.position);g.rotation.y=-a;const mat=new THREE.MeshBasicMaterial({color:0x66ffdb});for(const z of [-4.7,4.7]){const pole=new THREE.Mesh(new THREE.CylinderGeometry(.12,.12,5,6),mat);pole.position.set(z,2.5,0);g.add(pole)}const beam=new THREE.Mesh(new THREE.BoxGeometry(9.6,.22,.22),mat);beam.position.y=5;g.add(beam);scene.add(g)}
 for(const h of HAZARDS){const p=h.progress,a=p/101*Math.PI*2*turns;const color=h.type==='gap'?0xff6685:h.type==='wind'?0xffca70:0xff617b;const m=new THREE.Mesh(new THREE.BoxGeometry(2.5,h.type==='barrier'?.8:.15,1.5),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.5,transparent:true,opacity:.8}));pathPoint(p,h.lane,m.position);m.position.y+=.2;m.rotation.y=-a;scene.add(m)}
 for(const shortcut of SHORTCUTS){const p=shortcut.progress,m=new THREE.Mesh(new THREE.BoxGeometry(2.6,.35,3.8),new THREE.MeshStandardMaterial({color:0x54ffbe,emissive:0x25b980,emissiveIntensity:.5}));pathPoint(p,0,m.position);m.position.y+=.15;m.rotation.y=-p/101*Math.PI*2*turns;m.rotation.x=-.3;scene.add(m)}
 for(let p=5;p<101;p+=10){const m=new THREE.Mesh(new THREE.OctahedronGeometry(.7),new THREE.MeshStandardMaterial({color:0xffdc73,emissive:0xffb93d,emissiveIntensity:.5}));pathPoint(p,1,m.position);m.position.y+=1.6;scene.add(m);supplyViews.push({mesh:m,id:`supply-${(p-5)/10}`})}
 for(const item of ITEM_PICKUPS){const mesh=new THREE.Mesh(new THREE.BoxGeometry(1.3,1.3,1.3),new THREE.MeshStandardMaterial({color:0xbd84ff,emissive:0x8e42f5,emissiveIntensity:1,metalness:.2,roughness:.3}));pathPoint(item.progress,item.lane,mesh.position);mesh.position.y+=1.9;scene.add(mesh);itemViews.push({mesh,id:item.id})}
 const finish=new THREE.Mesh(new THREE.TorusGeometry(radiusAt(101)+7,.35,8,100),new THREE.MeshBasicMaterial({color:0xffd787}));finish.rotation.x=Math.PI/2;finish.position.y=202.1;scene.add(finish);
}
function scenery(){scene.background=new THREE.Color(0x101f42);scene.fog=new THREE.FogExp2(0x193357,.0018);scene.add(new THREE.HemisphereLight(0xb2e8ff,0x29334e,2.4));const sun=new THREE.DirectionalLight(0xffd4af,3);sun.position.set(90,220,100);scene.add(sun);const fill=new THREE.DirectionalLight(0x68b8ff,1.5);fill.position.set(-50,100,-90);scene.add(fill);const ground=new THREE.Mesh(new THREE.PlaneGeometry(2000,2000),new THREE.MeshStandardMaterial({color:0x11293d,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-1;scene.add(ground);
 const buildings=new THREE.InstancedMesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshStandardMaterial({color:0x28445b,metalness:.3,roughness:.8}),180);const d=new THREE.Object3D();let seed=37;const rng=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};for(let i=0;i<180;i++){const a=rng()*Math.PI*2,r=70+rng()*380,h=5+rng()*40;d.position.set(Math.cos(a)*r,h/2-1,Math.sin(a)*r);d.scale.set(7+rng()*14,h,7+rng()*14);d.rotation.y=rng()*.4;d.updateMatrix();buildings.setMatrixAt(i,d.matrix);buildings.setColorAt(i,new THREE.Color().setHSL(.57+rng()*.07,.22,.13+rng()*.12))}scene.add(buildings);
 const stars=[];for(let i=0;i<220;i++){const a=rng()*Math.PI*2,r=500;stars.push(Math.cos(a)*r,90+rng()*400,Math.sin(a)*r)}const sg=new THREE.BufferGeometry();sg.setAttribute('position',new THREE.Float32BufferAttribute(stars,3));scene.add(new THREE.Points(sg,new THREE.PointsMaterial({color:0xd7eaff,size:1.1,sizeAttenuation:true})));const moon=new THREE.Mesh(new THREE.SphereGeometry(12,24,16),new THREE.MeshBasicMaterial({color:0xffe7bc}));moon.position.set(-260,300,-380);scene.add(moon);
}
function effect(r,color){const m=new THREE.Mesh(new THREE.TorusGeometry(1,.14,6,36),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.9}));pathPoint(r.progress,r.x,m.position);m.position.y+=1.7;m.rotation.x=Math.PI/2;scene.add(m);effects.push({mesh:m,age:0})}
function handleEvents(){for(const e of race.events){if(e.id<=lastEvent)continue;lastEvent=e.id;if(e.racerId==='player'||e.targetId==='player'){ $('#feedback').textContent=e.message||'';$('#feedback').dataset.until=String(performance.now()+2200);beep(e.type.includes('perfect')?1000:e.type.includes('fall')?150:600,.16)}const r=race.racers.find(r=>r.id===e.racerId);if(r&&['attack','perfect','perfect-block','shield','dash'].some(t=>e.type.includes(t)))effect(r,e.type.includes('attack')?0xff9573:0x62ffe5)}}
function updateProjectiles(){const active=new Set();for(const shot of race.projectiles){active.add(shot.id);let m=projectileViews.get(shot.id);if(!m){m=new THREE.Mesh(new THREE.SphereGeometry(.6,12,8),new THREE.MeshBasicMaterial({color:0xd39aff}));scene.add(m);projectileViews.set(shot.id,m)}pathPoint(shot.progress,shot.lane,m.position);m.position.y+=1.8;m.scale.setScalar(1+Math.sin(performance.now()*.03)*.15)}for(const [id,m] of projectileViews){if(!active.has(id)){scene.remove(m);m.geometry.dispose();m.material.dispose();projectileViews.delete(id)}}}
function updateHud(){const p=race.racers[0];$('#clock').textContent=clockFormat(race.time);$('#floor').textContent=Math.floor(p.progress);$('#progress').style.width=`${p.progress/101*100}%`;$('#checkpoint').textContent=`檢查點 ${p.checkpoint}F · ${p.progress>90?'終點就在眼前':`下一站 ${Math.min(100,p.checkpoint+10)}F`}`;$('#energy').style.width=`${p.energy}%`;$('#energyValue').textContent=Math.round(p.energy);$('#standings').innerHTML=`<div class="eyebrow" style="font-size:10px">LIVE RANKING</div>`+[...race.racers].sort((a,b)=>b.progress-a.progress).map((r,i)=>`<div class="racerline ${r.id==='player'?'me':''}"><b>${i+1}</b><span>${r.name}${r.id==='player'?' · 你':''}</span><small>${Math.floor(r.progress)}F</small></div>`).join('');$('#ammo').textContent=p.ammo>0?(p.cooldowns.fire>0?`1 發 · ${p.cooldowns.fire.toFixed(1)}s`:'1 發 · 就緒'):'0 發 · 拾取紫箱';$('[data-action=fire]').classList.toggle('cooldown',!p.ammo||p.cooldowns.fire>0);for(const key of ['attack','shield','dash']){const c=p.cooldowns[key]||0;$(`#${key}Cd`).textContent=c>0?`${c.toFixed(1)}s`:'就緒';$(`[data-action=${key}]`).classList.toggle('cooldown',c>0)}$('#announcement').textContent=race.status==='countdown'?Math.ceil(race.countdown):p.fall>0?'安全繩救援中':p.stun>0?'遭到擊退！':'';if(performance.now()>+$('#feedback').dataset.until)$('#feedback').textContent='';}
function endRace(){resultShown=true;const order=[...race.racers].sort((a,b)=>b.progress-a.progress),win=race.winner==='player';if(race.racers[0].finished){records.push({name:race.racers[0].name,time:race.racers[0].finishTime||race.time});records.sort((a,b)=>a.time-b.time);records=records.slice(0,10);save('101-records',records)}showModal(`<div class="eyebrow">RACE COMPLETE</div><div class="winner">${win?'登頂冠軍！':'再挑戰一次！'}</div><p>${win?'台北的天空，屬於你。':`${order[0].name}率先抵達101F。下次看準時機，完美格擋！`} · ${clockFormat(race.time)}</p>${order.map((r,i)=>`<div class="results"><span>${i+1}. ${r.name}${r.id==='player'?'（你）':''}</span><b>${Math.floor(r.progress)}F</b></div>`).join('')}<button class="primary" id="again">再比一場</button><button id="backMenu" style="width:100%;margin-top:10px">更換寶可夢</button>`);$('#again').onclick=startRace;$('#backMenu').onclick=goMenu;resumeAfterModal=false;beep(win?1200:300,.5)}
async function init(){try{const canvas=$('#world');const context=canvas.getContext('webgl2',{antialias:true,alpha:false});if(!context)throw new Error('WEBGL2');renderer=new THREE.WebGLRenderer({canvas,context,antialias:true});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;applyQuality();scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.1,2000);scenery();const loader=new GLTFLoader();let count=0;const list=['Taipei101',...CHARACTERS.map(c=>c.id)];for(const id of list){$('#loadText').textContent=`載入 ${id} · ${count+1} / ${list.length}`;const gltf=await loader.loadAsync(`${import.meta.env.BASE_URL}models/${id}.glb`);const model=optimize(gltf.scene);if(id==='Taipei101'){tower=model;tower.scale.setScalar(202/508);scene.add(tower)}else templates.set(id,normalize(model,id==='Rayquaza'?5:3.7));$('#loadFill').style.width=`${++count/list.length*100}%`;}buildTrack();loaded=true;makePreview();$('#load').classList.add('hidden');$('#menu').classList.remove('hidden');resize();requestAnimationFrame(frame);window.__game={get race(){return race},get loaded(){return loaded},startRace,goMenu,stepRace,templates,renderer,scene};}catch(e){console.error(e);$('#load').innerHTML=`<div class="eyebrow">${e.message==='WEBGL2'?'3D 支援檢查':'載入未完成'}</div><h1>${e.message==='WEBGL2'?'需要支援 WebGL 2 的瀏覽器':'素材載入失敗'}</h1><p>${e.message==='WEBGL2'?'請在最新版 Chrome、Edge、Firefox 或 Safari 開啟，並啟用瀏覽器硬體加速。<br>這是真正的3D遊戲，無法以2D模式替代。':'請確認網路與 models 資料夾完整，透過 HTTP 伺服器開啟。'}</p><button onclick="location.reload()">重新檢查</button>`;}}
function resize(){if(!renderer)return;renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);
function readInput(){return {forward:keys.has('KeyS')||keys.has('ArrowDown')?-1:settings.autoRun||keys.has('KeyW')||keys.has('ArrowUp')||touch.forward?1:0,lane:(keys.has('KeyA')||keys.has('ArrowLeft')||touch.left?1:0)-(keys.has('KeyD')||keys.has('ArrowRight')||touch.right?1:0),...actionQueue}}
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000);last=now;if(playing&&race){if(!paused){const input=readInput();stepRace(race,dt,input);Object.keys(actionQueue).forEach(k=>delete actionQueue[k]);handleEvents();updateHud();if(race.status==='finished'&&!resultShown)endRace()}
 const p=race.racers[0];supplyViews.forEach(v=>{v.mesh.visible=!p._supplies[v.id];v.mesh.rotation.y=now*.0015});itemViews.forEach(v=>{v.mesh.visible=!p._items?.[v.id];v.mesh.rotation.y=now*.0018;v.mesh.rotation.z=Math.sin(now*.001)*.2});updateProjectiles();race.racers.forEach((r,i)=>{const v=actorViews[i],a=r.progress/101*Math.PI*2*turns;pathPoint(r.progress,r.x,v.g.position);v.g.position.y+=r.jump>0?r.jumpHeight*2.7:Math.sin(now*.012+i)*.08;v.g.position.y-=r.fall>0?Math.sin(now*.012)*.7:0;v.g.rotation.y=-a;v.model.rotation.z=r.stun>0?Math.sin(now*.025)*.3:Math.sin(now*.01+i)*.025;v.shield.visible=r.shield>0;v.shield.rotation.y=now*.001;v.ring.material.color.set(r.attackWindup>0?0xff5b63:(i===0?0x63f5df:CHARACTERS.find(c=>c.id===r.characterId).color));v.ring.scale.setScalar(r.attackWindup>0?1.4:1);v.ring.material.opacity=.7});const a=p.progress/101*Math.PI*2*turns;pathPoint(p.progress,p.x,target);target.y+=3;const pose=cameraPose(target,a,radiusAt(p.progress),orbit);vec.set(pose.x,pose.y,pose.z);camera.position.lerp(vec,1-Math.exp(-dt*6));keepOutsideTower(camera.position,radiusAt(p.progress)+2.5,a);camera.lookAt(target);}
 else{menuAngle+=dt*.045;camera.position.set(Math.cos(menuAngle)*260,137,Math.sin(menuAngle)*260);camera.lookAt(0,95,0);if(preview)preview.rotation.y+=dt*.5;}
 for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.age+=dt;e.mesh.scale.setScalar(1+e.age*14);e.mesh.material.opacity=Math.max(0,1-e.age*1.5);if(e.age>.7){scene.remove(e.mesh);e.mesh.geometry.dispose();e.mesh.material.dispose();effects.splice(i,1)}}renderer.render(scene,camera);}
init();
